version: '3'
services:
  users:
      build:
        context: ./services/users
        dockerfile: Dockerfile
      volumes:
        - './services/users:/usr/src/app'
      ports:
        - 5001:5000
      environment:
          - FLASK_APP=app/__init__.py
          - FLASK_ENV=development
          - APP_SETTINGS=app.config.DevelopmentConfig